name: Daily Upload

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  Daily-Upload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: |
          chmod +x ./deps_install.sh && ./deps_install.sh
          pip install -r requirements.txt
      - name: Run code
        env:
          YOUTUBE_TOKEN: ${{ secrets.YOUTUBE_TOKEN }}
        run: python3 main.py --production --token $YOUTUBE_TOKEN --transcribe
      
      - name: archive captions
        uses: actions/upload-artifact@v4
        with:
          name: captions
          path: *.srt
